# Generated by Django 4.0.2 on 2022-03-27 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teach_id', models.AutoField(primary_key=True, serialize=False)),
                ('teach_dept_name', models.CharField(max_length=25)),
                ('teach_designation', models.CharField(max_length=100)),
                ('teach_dob', models.DateField()),
                ('teach_phone', models.IntegerField()),
                ('teach_image', models.FileField(upload_to='images')),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
