# Generated by Django 4.0.2 on 2022-04-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_teacher_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('sub_code', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=200)),
                ('dept_name', models.CharField(max_length=200)),
                ('semester', models.IntegerField()),
            ],
        ),
    ]
