# Generated by Django 4.0.2 on 2022-04-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time_table',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('semester', models.CharField(max_length=200)),
                ('dept', models.CharField(max_length=200)),
                ('subjects', models.CharField(max_length=200)),
                ('tutor', models.CharField(max_length=200)),
                ('day', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=200)),
            ],
        ),
    ]
