# Generated by Django 4.0.2 on 2022-04-17 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_internal_exams'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Internal_exams',
        ),
    ]
