# Generated by Django 4.0.2 on 2022-03-31 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hod', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hod',
            name='hod_image',
            field=models.FileField(upload_to='images'),
        ),
    ]
