# Generated by Django 4.0.2 on 2022-04-02 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_teacher_group'),
        ('hod', '0002_alter_hod_hod_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='tutor_allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('dept_name', models.CharField(max_length=200)),
                ('batch', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('hod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hod.hod')),
                ('teach_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher')),
            ],
        ),
    ]
