# Generated by Django 4.0.2 on 2022-04-02 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hod', '0003_tutor_allocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor_allocation',
            name='hod_id',
        ),
        migrations.RemoveField(
            model_name='tutor_allocation',
            name='teach_id',
        ),
        migrations.AddField(
            model_name='tutor_allocation',
            name='tutor',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
