# Generated by Django 4.0.2 on 2022-04-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hod', '0004_remove_tutor_allocation_hod_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject_allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutor', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('dept_name', models.CharField(max_length=200)),
                ('batch', models.CharField(max_length=200)),
                ('date', models.DateField()),
            ],
        ),
    ]
