# Generated by Django 4.0.2 on 2022-04-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hod', '0006_placement_coordinator_time_table_coordinator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam_coordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('dept_name', models.CharField(max_length=200)),
                ('date', models.DateField()),
            ],
        ),
    ]
